### ISSUE TITLE
Bookmark sign blinks in gutter

### ISSUE THREAD

**Issue by oblitum** [voldikss/coc-bookmark#2] opened 2019-07-23 21:43 UTC
I don't know the reason but I can notice the bookmark sign blinking in the gutter (I'm using Alacritty with is faster than normal), while other gutter signs don't do the same,  maybe it's an issue with timers and refresh?

**Comment by voldikss** [comment] 2019-07-23 23:41
Thanks for this. It's caused by updating signs, this issues will be fixed as soon as I find a new method a refresh signs.

**Closed** 2019-07-24 14:52 UTC
Labels: bug

**Comment by voldikss** [comment] 2019-07-24 14:57
@oblitum  I think this issue has been fixed. It's gone when I tested on my laptop.

**Comment by oblitum** [comment] 2019-07-24 15:42
Yes indeed, thanks!

I have one curiosity about where annotations are going to be saved, maybe it should be documented in docs, for the case someone wishes to move them to another machine?

**Comment by oblitum** [comment] 2019-07-24 15:46
Also, I noticed in code that you need to set both signal foreground and background for it to take effect, setting just one will do nothing. Maybe the highlighting group should also be exposed in doc? I'm currently simply ignoring `signFg` and `signBg` and instead setting it through `hi! link BookMarkHI CocInfoSign`.

**Comment by oblitum** [comment] 2019-07-24 16:00
> I noticed in code that you need to set both signal foreground and background for it to take effect, setting just one will do nothing.

Ops, sorry, just noticed this part was fixed.

**Comment by voldikss** [comment] 2019-07-24 22:45
> I have one curiosity about where annotations are going to be saved

Most Coc extension save their data here `~/.config/coc/extensions/data/coc-xxx-data/`. Thank， this will be added to the document soon.
